package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// S3API is an autogenerated mock type for the S3API type
type Postgres struct {
	mock.Mock
}

// func (_m *postgres) query(_a0 qrm.Query, _a1 qrm.queryToSlice) {

// }
